# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-10 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0007_label_and_emailattachmenttemplates'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='template',
            field=models.CharField(choices=[('post_office/base_mail.html', 'Base Mail')], default='post_office/base_mail.html', help_text='The mail template used to render the content.', max_length=100, verbose_name='template'),
        ),
    ]
