# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-10 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import post_office.validators


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0008_emailtemplate_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='template',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='content_data',
            field=models.TextField(blank=True, help_text="The fields between '{{' and '}}' are the variables while the text that is included in the tags '{% comment%}' and '{% endcomment%}' will not be rendered in the mail                                                                                     <br/> Do not remove the fields included in the tags '{%' '%}'", validators=[post_office.validators.validate_template_syntax], verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='template_name',
            field=models.CharField(blank=True, choices=[('post_office/base_mail.html', 'Base Mail')], help_text='The mail template used to render the content.', max_length=100, verbose_name='template'),
        ),
    ]
