# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0009_auto_20180710_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='template_name',
            new_name='template_path',
        ),
    ]
