# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 16:16
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.translation import ugettext_lazy as _
from post_office.settings import get_base_email_templates

TEMPLATE_CHOICES = [(x, _(y)) for x, y in get_base_email_templates()]

"""
Migration hacked to avoid other migrations after user customization
Thanks to djangocms 0001 migration for the idea
"""

class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0010_auto_20180711_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_path',
            field=models.CharField(blank=True, choices=TEMPLATE_CHOICES, help_text='The mail template used to render the content.', max_length=100, verbose_name='template'),
        ),
    ]
