# Generated by Django 2.2.12 on 2020-05-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0011_auto_20180718_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='footer_text',
            field=models.TextField(blank=True, verbose_name='Footer text'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='header_image',
            field=models.ImageField(blank=True, help_text="E' consigliabile inserire un'immgine con dimensioni 650x325", null=True, upload_to='uploads/img', verbose_name='Header Image'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='sign',
            field=models.CharField(blank=True, max_length=500, verbose_name='Sign'),
        ),
    ]
