# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 15:25
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.translation import ugettext_lazy as _
from post_office.settings import get_base_languages

LANGUAGES_CHOICES = [(x, _(y)) for x, y in get_base_languages()]

"""
Migration hacked to avoid other migrations after user customization
Thanks to djangocms 0001 migration for the idea
"""

class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0011_auto_20180718_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmenttemplate',
            name='language',
            field=models.CharField(blank=True, choices=LANGUAGES_CHOICES, default='', help_text='Attachment in alternative language', max_length=12, verbose_name='Language'),
        ),
    ]
